Mable/GraphQLHelperSpecs:
  Description: 'Avoid hardcoding GraphQl path use helper instead.'
  Enabled: true
  VersionAdded: '0.1.2'

Mable/HardcodedDatabaseFactoryBotId:
  Enabled: true
  Description: 'Avoid hardcoding factory bot database IDs, instead, dynamically test for the ID'
  VersionAdded: '0.1.1'

Mable/NoSafetyAssured:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '<<next>>'
