Mable/GraphQLHelperSpecs:
  Description: "Avoid hardcoding GraphQl path use helper instead."
  Enabled: true
  VersionAdded: "0.1.2"

Mable/HardcodedDatabaseFactoryBotId:
  Enabled: true
  Description: "Avoid hardcoding factory bot database IDs, instead, dynamically test for the ID"
  VersionAdded: "0.1.1"

Mable/NoSafetyAssured:
  Description: "An extra check to ensure that the safety_assured is required"
  Enabled: true
  VersionAdded: "0.1.3"

Mable/NoPostInGraphQL:
  Description: "Use graphQL helper method instead of use rails/rack request stack"
  Enabled: true
  VersionAdded: "0.1.4"
  ReplacePostWith: "make_graphql_request"
  SafeAutoCorrect: false
  AllowedGraphQLPaths:
    - "/graphql"
    - "graphql_path"

Mable/NoWardenInGraphQL:
  Description: "No Warden in graphQL use helper method instead see - Mable/NoPostInGraphQL"
  Enabled: true
  SafeAutoCorrect: false
  VersionAdded: "0.1.5"
